// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plwvrsxgmtwnxfljoxai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsd3Zyc3hnbXR3bnhmbGpveGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NzAwNDgsImV4cCI6MjA2MDI0NjA0OH0.grKDrKC-vyS705hRpIoHPa4Xk-eWi19Q8pRV5tRz_0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);